name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Build
      run: |
        cd /home/github/Notes
        sudo git pull
        sudo /usr/local/bin/vuepress build docs
    - name: Test
      run: |
        curl -I http://leohsiao.com/ --connect-timeout 3