name: Deploy

on: [push]

jobs:
  build-vuepress:
    runs-on: self-hosted
    steps:
    - name: Build
      run: |
        cd /home/github/Notes
        git pull
        yarn
        yarn vuepress build docs || yarn vuepress build docs  # 构建时可能因为占用内存不足而被杀死，因此尝试执行两次
        cd docs/.vuepress/
        mkdir -p stable_dist/
        rm -rf stable_dist/*
        cp -r dist/* stable_dist/

    - name: Test
      run: |
        curl -I http://leohsiao.com/ --connect-timeout 3
        curl http://leohsiao.com:7700/indexes --connect-timeout 3
  
  scrap-docs:
    needs: build-vuepress
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Run docs-scraper
      env:
        API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
      run: |
        docker run -t --rm \
          -e MEILISEARCH_HOST_URL='http://leohsiao.com:7700' \
          -e MEILISEARCH_API_KEY=$API_KEY \
          -v $PWD/etc/docs-scraper.json:/docs-scraper/config.json \
          getmeili/docs-scraper:v0.10.2 pipenv run ./docs_scraper config.json
