name: Deploy

on: [push]

jobs:
  build-vuepress:
    runs-on: self-hosted
    steps:
    - name: Build
      run: |
        cd /home/github/Notes
        git pull
        yarn
        yarn vuepress build docs
    - name: Test
      run: |
        curl -I http://leohsiao.com/ --connect-timeout 3
  
  scrap-docs:
    needs: build-vuepress
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Run docs-scraper
      env:
        API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
        CONFIG_FILE_PATH: ${{ github.workspace }}/etc/docs-scraper.json
      run: |
        docker run -t --rm \
          -e MEILISEARCH_HOST_URL='http://leohsiao.com:7700' \
          -e MEILISEARCH_API_KEY=$API_KEY \
          -v $CONFIG_FILE_PATH:/docs-scraper/config.json \
          getmeili/docs-scraper:v0.9.0 pipenv run ./docs_scraper config.json
