name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build_vuepress:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        yarn
        yarn vuepress build docs
        mv docs/.vuepress/dist .
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist
        retention-days: 1

  copy_dist:
    needs: build_vuepress
    runs-on: self-hosted
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Copy dist
      run: |
        set -eu
        rm -rf  $DEPLOY_DIR/*
        cp -r   dist/*  $DEPLOY_DIR
      env:
        DEPLOY_DIR: /data/Notes/

  test_website:
    needs: copy_dist
    runs-on: ubuntu-20.04
    steps:
    - name: Test
      run: |
        curl https://leohsiao.com --connect-timeout 5
        curl https://meilisearch.leohsiao.com/health --connect-timeout 5

  scrap_docs:
    needs: test_website
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Run docs-scraper
      env:
        API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
      run: |
        docker run -t --rm \
          -e MEILISEARCH_HOST_URL=https://meilisearch.leohsiao.com \
          -e MEILISEARCH_API_KEY=$API_KEY \
          -v $PWD/etc/docs-scraper.json:/docs-scraper/config.json \
          getmeili/docs-scraper:v0.11.0 pipenv run ./docs_scraper config.json
