# This script is used to test GitHub Actions.

name: Test Actions

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
    - name: Touch
      run: |
        touch f1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      # with:
      #   vs-version: '[16.4,16.5)'
