# This script is used to test GitHub Actions.

name: Test Actions

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build something requiring CL.EXE
      run: |
        cmake -G "NMake Makefiles" .
        nmake
    - name: Run msbuild
      run: |
        msbuild
        cl
