# This script is used to test GitHub Actions.

name: Test Actions

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
    - name: Touch
      run: |
        touch f1

    - name: Check
      run: |
        pwd
        ls -al

  job2:
    runs-on: ubuntu-18.04
    steps:
    - name: Check
      run: |
        pwd
        ls -al

